name: Publish HTTP Errors package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/http-errors/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v1
      name: checkout
    - uses: actions/setup-node@v1
      name: Install node.js
      with:
        node-version: '10.x'
    - run: npm install
      name: Install dependencies
      working-directory: packages/http-errors
    - run: npm run test:prod && npm run build
      name: Build
      working-directory: packages/http-errors
    - run: npm run semantic-release
      name: Publish
      working-directory: packages/http-errors
      env:
        GIT_AUTHOR_NAME: matejicekme
        GIT_AUTHOR_EMAIL: jordan@owlie.xyz
        GIT_COMMITTER_NAME: JordanOwlie
        GIT_COMMITTER_EMAIL: jordan@owlie.xyz
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}