name: Publish Uploader package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/uploader/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v1
      name: checkout
    - uses: actions/setup-node@v1
      name: Install node.js
      with:
        node-version: '10.x'
    - run: npm install
      name: Install dependencies
      working-directory: packages/uploader
    - run: npm run test:prod && npm run build
      name: Build
      working-directory: packages/uploader
      env:
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        FIREBASE_BUCKET: ${{ secrets.FIREBASE_BUCKET }}
    - run: npm run semantic-release
      name: Publish
      working-directory: packages/uploader
      env:
        GIT_AUTHOR_NAME: matejicekme
        GIT_AUTHOR_EMAIL: jordan@owlie.xyz
        GIT_COMMITTER_NAME: JordanOwlie
        GIT_COMMITTER_EMAIL: jordan@owlie.xyz
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
